//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.SalesInvoices = new HashSet<SalesInvoice>();
            this.SalesInvoiceEntries = new HashSet<SalesInvoiceEntry>();
            this.SystemLogs = new HashSet<SystemLog>();
            this.Vouchers = new HashSet<Voucher>();
            this.VoucherEntries = new HashSet<VoucherEntry>();
        }
    
        public int ID { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Firstname { get; set; }
        public string MiddleName { get; set; }
        public string Lastname { get; set; }
        public string Email { get; set; }
        public int Role { get; set; }
        public System.DateTime DateAdded { get; set; }
        public Nullable<System.DateTime> DateLastLogin { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<SalesInvoice> SalesInvoices { get; set; }
        public virtual ICollection<SalesInvoiceEntry> SalesInvoiceEntries { get; set; }
        public virtual ICollection<SystemLog> SystemLogs { get; set; }
        public virtual ICollection<Voucher> Vouchers { get; set; }
        public virtual ICollection<VoucherEntry> VoucherEntries { get; set; }
    }
}
